package constants

const (
  DEFINE           = "define"
  BEGIN            = "begin"
  SET              = "set!"
  LAMBDA           = "lambda"
  LET              = "let"
  LET_STAR         = "let*"
  LET_REC          = "letrec"
  OPEN_PARANT      = "("
  CLOSE_PARANT     = ")"
  ADD              = "+"
  SUB              = "-"
  MULT             = "*"
  DIV              = "/"
  DOT              = "."
  QUOTE            = "quote"
  QUASIQUOTE       = "quasiquote"
  UNQUOTE          = "unquote"
  UNQUOTE_SPLICING = "unquote-splicing"
  APPLY            = "apply"
  IF               = "if"
  COND             = "cond"
  DELAY            = "delay"
  FORCE            = "force"
  GO               = "go"
  CHAN_SEND        = "chan<-"
  CHAN_RECV        = "<-chan"
  SELECT           = "select"
)
