package constants

const (
  DEFINE           = "define"
  BEGIN            = "begin"
  LET              = "let"
  SET              = "set!"
  LAMBDA           = "lambda"
  OPEN_PARANT      = "("
  CLOSE_PARANT     = ")"
  ADD              = "+"
  SUB              = "-"
  MULT             = "*"
  DIV              = "/"
  DOT              = "."
  QUOTE            = "quote"
  QUASIQUOTE       = "quasiquote"
  UNQUOTE          = "unquote"
  UNQUOTE_SPLICING = "unquote-splicing"
  IF               = "if"
  COND             = "cond"
  GO               = "go"
  CHAN_SEND        = "chan<-"
  CHAN_RECV        = "chan->"
  SELECT           = "select"
)
